databases:
  - name: "auth"
    host: "auth-db"
    user: "auth"
    password: "auth"
    port: 5432
    file: "./auth"
  - name: "event"
    host: "event-db"
    user: "event"
    password: "event"
    port: 5432
