databases:
  - name: "auth"
    host: "localhost"
    user: "auth"
    password: "auth"
    port: 5432
    file: "./auth"
  - name: "event"
    host: "localhost"
    user: "event"
    password: "event"
    port: 5433
